# Generated by Django 4.0.3 on 2022-04-09 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekshopping', to='hesab.week'),
        ),
    ]
