# Generated by Django 4.0.3 on 2022-04-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0005_alter_shopping_name_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
