# Generated by Django 4.0.3 on 2022-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0006_alter_money_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
